stages:
   - Building & migration

build:
  stage: Building & migration
  commands:
     - ls

pre-build:
  script:
    - ls

post-build:
  script:
    - ls -la

projects:
    - name: Angular
      build-platform: node:10.16.3-alpine as build-env
      build-commands:
        - apk update && apk add git
        - CHECKOUT
        - cd web-ui && npm install
        - cd web-ui && node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build  && mv dist /tmp
        - cd conf && mv vhost.conf /tmp/vhost.conf
      platform: alpine:latest
      commands:
        - apk update --no-cache && apk add apache2
        - sed -i '/LoadModule rewrite_module/s/^#//g' /etc/apache2/httpd.conf && sed -i 's#AllowOverride [Nn]one#AllowOverride All#' /etc/apache2/httpd.conf
      copy: 
        - --from=build-env /tmp/dist/web-ui /var/www/dist
        - --from=build-env /tmp/vhost.conf /etc/apache2/conf.d/vhost.conf
      expose: 80
      to-start:
        - httpd -D FOREGROUND
      service:
        - name: spritle-angular-dev
          port: 80
      host:
        - name: spritle-soft.in
    - name: Django
      platform: alpine:latest
      commands:
        - apk update --no-cache && apk upgrade && apk add git python3 python3-dev gcc musl-dev libc-dev mysql-client mysql-dev py3-pip  make automake autoconf
        - CHECKOUT
        - cd django && pip3 install -r requirements
      to-start:
        - cd django && python3 manage.py runserver 0.0.0.0:8000
      service:
        - name: spritle-django-dev
          port: 8000
      host:
        - name: spritle-softbck.in

